CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('manager', 'employee') NOT NULL,
    image VARCHAR(1024) DEFAULT NULL,
    theme VARCHAR(20) DEFAULT 'light',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Projects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    createdBy INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (createdBy) REFERENCES Users(id)
);

CREATE TABLE Tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    status ENUM('TODO', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'CANCELLED') DEFAULT 'TODO',
    priority ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT') DEFAULT 'MEDIUM',
    progress INT DEFAULT 0,
    createdBy INT NOT NULL,
    assignedTo INT DEFAULT NULL,
    projectId INT NOT NULL,
    dueDate DATETIME DEFAULT NULL,
    startDate DATETIME DEFAULT NULL,
    completedAt DATETIME DEFAULT NULL,
    tags JSON,
    isDeleted BOOLEAN DEFAULT FALSE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (createdBy) REFERENCES Users(id),
    FOREIGN KEY (assignedTo) REFERENCES Users(id),
    FOREIGN KEY (projectId) REFERENCES Projects(id)
);

CREATE TABLE TaskComments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    taskId INT NOT NULL,
    userId INT NOT NULL,
    message TEXT NOT NULL,
    isEdited BOOLEAN DEFAULT FALSE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (taskId) REFERENCES Tasks(id),
    FOREIGN KEY (userId) REFERENCES Users(id)
);